use_frameworks!

platform :ios, '8.0'

target 'HKUIAddtion_Example' do
  pod 'HKUIAddtion', :path => '../'

  target 'HKUIAddtion_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
